name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      BUILD_BUILDNUMBER: "3.0.0.${{ github.run_number }}"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Build
      run: msbuild Cassia.targets

    - name: Publish package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Package
        path: "Bin/Publish/Cassia-${{ env.BUILD_BUILDNUMBER }}.zip"
    - name: Publish NuGet
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NuGet
        path: "Bin/Publish/Cassia.${{ env.BUILD_BUILDNUMBER }}.nupkg"
